server:
  port: 8070
  servlet:
    context-path: /user-managment

spring:
  application:
    name: user-service # application name
  config:
    import: "optional:configserver:"
  data:
    mongodb:
      uri: mongodb+srv://BDD:*BDD2022*@quizz-cluster.iq9wt.mongodb.net/user-db
      database: user-db

app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000