server:
  port: 8000

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      routes:
        - id: user-service-id
          uri: lb://user-service
          predicates:
            - Path=/user-managment/**
          filters:
            - JwtCustomFilter

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
