server:
  port: 8080

spring:
  config:
    import: "optional:configserver:"
  application:
    name: quizz-manager
  data:
    mongodb:
      uri: mongodb+srv://BDD:*BDD2022*@quizz-cluster.iq9wt.mongodb.net/quizz-db
      database: quizz-db